### ISSUE TITLE
Option in the config to not display empty signs

### ISSUE THREAD

**Issue by mikinol** [TechnicJelle/BlueMapSignExtractor#63] opened 2024-11-09 15:18 UTC

**Comment by TechnicJelle** [comment] 2024-11-09 15:20
I'm working on it...
But I've had so little time, and also I'm likely going to rethink the whole thing....
Duplicate of #50.

In the meantime, you could maybe use #38

**Closed by TechnicJelle** 2024-11-09 15:20 UTC
Labels: duplicate

**Comment by TechnicJelle** [comment] 2024-11-09 15:24
Ah, I suppose I should merge that PR in the meantime...
I won't be able to add this feature in the better way that I wanted to do soon enough.

**Comment by TechnicJelle** [comment] 2024-11-16 16:37
Done in https://github.com/TechnicJelle/BlueMapSignExtractor/releases/tag/v1.4
